spring.config.import=file:env.properties
spring.application.name=u5w2test
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
server.port=${PORT}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
cloudinary.apikey=${CLOUDINARY_KEY}
cloudinary.secret=${CLOUDINARY_SECRET}
cloudinary.name=${CLOUDINARY_NAME}

